### ISSUE TITLE
Theme reverts back after minimizing Telegram. 

### ISSUE THREAD

**Issue by pras92** [dracula/telegram-android#2]
Thank you @huezo for creating such a beautiful theme. 

I can install it fine but, everytime I close or even minimize the app, Telegram reverts back to default dark theme which I believe is in-line with system wide Android Dark mode. I can see that Dracula is still the selected theme however, it isn't displayed. 

Can I somehow use Dracula while still retaining the Android Dark mode? I'm able to use other apps unaffected by Android's system wide dark mode. 

OS: Android 10.

**Comment by CH4ND4N-x** [comment]
Facing the same issue, it revert back to default theme everytime I close the reopen the app

**Comment by r0hitm** [comment]
Facing similar issue. Plus if I deselect and select dracula theme again from the settings, the theme reverts back in around 2-3 seconds, even without closing the app

**Comment by r0hitm** [comment]
I found the solution, __make sure telegram's inbuilt dark mode is off__
![photo_2021-08-16_10-57-12](https://user-images.githubusercontent.com/63762981/129515736-0b469d94-aa47-440a-9fba-6f10d45641f8.jpg)

**Comment by pras92** [comment]
@hiro776  That worked! Such a simple solution, thanks.

**Comment by huezo** [comment]
@pras92 

I'm so glad you like it, the Theme! **Thank you so much!**
