### ISSUE TITLE
Muted unread chats are not distinguishable from unread chats

### ISSUE THREAD

**Issue by 8549** [dracula/telegram-android#3]
![image](https://user-images.githubusercontent.com/15671077/118111114-8b3e5c00-b3e3-11eb-88b9-878216ddd02e.png)
![Screenshot_20210513-121345](https://user-images.githubusercontent.com/15671077/118112405-3e5b8500-b3e5-11eb-994b-0d105145b205.png)

It would be nice to reflect the same color/alpha value used in the Telegram Desktop theme (the same color is already present in this theme but used for other variables).

**Comment by zenorocha** [comment]
Can you take a look @huezo?

**Comment by huezo** [comment]
@8549

Thank!

**Comment by huezo** [comment]
> Can you take a look @huezo?

I'm going to fix it

**Comment by huezo** [comment]
> ![image](https://user-images.githubusercontent.com/15671077/118111114-8b3e5c00-b3e3-11eb-88b9-878216ddd02e.png)
> ![Screenshot_20210513-121345](https://user-images.githubusercontent.com/15671077/118112405-3e5b8500-b3e5-11eb-994b-0d105145b205.png)
> 
> It would be nice to reflect the same color/alpha value used in the Telegram Desktop theme (the same color is already present in this theme but used for other variables).

Fix
https://github.com/dracula/telegram-android/releases/tag/2021.8.28

**Comment by 8549** [comment]
Thank you, now it's better, but i feel the two colors are somewhat too difficult to tell apart. Could you unify the color scheme to the Desktop version (screenshot below)? Thanks.

![image](https://user-images.githubusercontent.com/15671077/131319908-aa4b3578-a7d0-4db0-a8d0-3e56c8c727ec.png)
